module,execution_time (sec),success,timestamp,error,error_short
cowidev.vax.batch.argentina,15.5,True,2023-04-22T07:00:22,,
cowidev.vax.batch.australia,0.24,False,2023-04-22T07:03:03,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/australia.py"", line 244, in main
    Australia().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/australia.py"", line 216, in export
    df = self.read().pipe(self.pipeline)  # Use with attach=False
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/australia.py"", line 160, in pipeline
    .pipe(self.make_monotonic)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/utils/base.py"", line 120, in make_monotonic
    return mkm(
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/utils.py"", line 23, in make_monotonic
    return make_monotonic_new(df, column_date, column_metrics, max_removed_rows)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/utils.py"", line 94, in make_monotonic_new
    raise Exception(
Exception: 1 chunks of lengths 19 have been NaNed for metric people_vaccinated. That is more than maximum allowed (10) by make_monotonic() - check the data. Check dates ['2023-03-16']
",1 chunks of lengths 19 have been NaNed for metric people_vaccinated. That is more than maximum allowed (10) by make_monotonic() - check the data. Check dates ['2023-03-16']
cowidev.vax.batch.austria_old,,,2023-04-22T07:00:06,,
cowidev.vax.batch.belgium,11.48,True,2023-04-22T07:00:18,,
cowidev.vax.batch.bolivia,4.74,True,2023-04-22T07:00:11,,
cowidev.vax.batch.canada,6.99,False,2023-04-22T07:03:10,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/canada.py"", line 282, in main
    Canada().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/canada.py"", line 270, in export
    df = df.pipe(self.pipeline, df_man)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/canada.py"", line 250, in pipeline
    .pipe(self.pipe_make_monotonic)[
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/canada.py"", line 230, in pipe_make_monotonic
    df = df.pipe(self.make_monotonic, max_removed_rows=self.max_removed_rows)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/utils/base.py"", line 120, in make_monotonic
    return mkm(
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/utils.py"", line 23, in make_monotonic
    return make_monotonic_new(df, column_date, column_metrics, max_removed_rows)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/utils.py"", line 94, in make_monotonic_new
    raise Exception(
Exception: 1 chunks of lengths 36 have been NaNed for metric people_vaccinated. That is more than maximum allowed (22) by make_monotonic() - check the data. Check dates ['2023-01-26']
",1 chunks of lengths 36 have been NaNed for metric people_vaccinated. That is more than maximum allowed (22) by make_monotonic() - check the data. Check dates ['2023-01-26']
cowidev.vax.batch.chile,1.02,True,2023-04-22T07:00:08,,
cowidev.vax.batch.czechia,2.54,True,2023-04-22T07:03:12,,
cowidev.vax.batch.denmark,,,2023-04-22T07:00:06,,
cowidev.vax.batch.ecdc,99.67,True,2023-04-22T07:01:46,,
cowidev.vax.batch.ecuador,,,2023-04-22T07:00:06,,
cowidev.vax.batch.estonia,0.86,True,2023-04-22T07:00:07,,
cowidev.vax.batch.france,9.15,True,2023-04-22T07:00:16,,
cowidev.vax.batch.germany,0.31,True,2023-04-22T07:00:07,,
cowidev.vax.batch.greece,16.96,True,2023-04-22T07:00:23,,
cowidev.vax.batch.hong_kong,18.86,True,2023-04-22T07:00:25,,
cowidev.vax.batch.indonesia,,,2023-04-22T07:00:06,,
cowidev.vax.batch.ireland,5.91,True,2023-04-22T07:00:12,,
cowidev.vax.batch.israel,9.63,True,2023-04-22T07:00:16,,
cowidev.vax.batch.italy,8.96,True,2023-04-22T07:00:15,,
cowidev.vax.batch.japan,41.96,True,2023-04-22T07:00:48,,
cowidev.vax.batch.jersey,8.09,True,2023-04-22T07:00:15,,
cowidev.vax.batch.latvia,71.8,True,2023-04-22T07:01:18,,
cowidev.vax.batch.lithuania,7.77,True,2023-04-22T07:00:14,,
cowidev.vax.batch.luxembourg,3.94,True,2023-04-22T07:00:10,,
cowidev.vax.batch.malaysia,0.81,True,2023-04-22T07:00:07,,
cowidev.vax.batch.malta,1.11,True,2023-04-22T07:00:08,,
cowidev.vax.batch.netherlands,,,2023-04-22T07:00:06,,
cowidev.vax.batch.new_zealand,14.36,True,2023-04-22T07:00:21,,
cowidev.vax.batch.norway,0.4,True,2023-04-22T07:00:07,,
cowidev.vax.batch.peru,4.47,True,2023-04-22T07:00:11,,
cowidev.vax.batch.portugal,,,2023-04-22T07:00:06,,
cowidev.vax.batch.romania,34.2,True,2023-04-22T07:00:41,,
cowidev.vax.batch.saudi_arabia,9.98,True,2023-04-22T07:00:16,,
cowidev.vax.batch.singapore,7.58,True,2023-04-22T07:00:14,,
cowidev.vax.batch.slovakia,55.32,True,2023-04-22T07:01:02,,
cowidev.vax.batch.slovenia,4.75,True,2023-04-22T07:00:11,,
cowidev.vax.batch.south_korea,36.52,False,2023-04-22T07:03:49,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/south_korea.py"", line 209, in main
    SouthKorea().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/south_korea.py"", line 191, in export
    df_base = self.read().pipe(self.pipeline_base)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/south_korea.py"", line 107, in pipeline_base
    df.pipe(self.pipe_drop_columns)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/south_korea.py"", line 51, in pipe_drop_columns
    df = df.drop(columns=[""동절기""], level=0)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/util/_decorators.py"", line 311, in wrapper
    return func(*args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/frame.py"", line 4906, in drop
    return super().drop(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 4150, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 4183, in _drop_axis
    new_axis = axis.drop(labels, level=level, errors=errors)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/indexes/multi.py"", line 2190, in drop
    return self._drop_from_level(codes, level, errors)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/indexes/multi.py"", line 2242, in _drop_from_level
    raise KeyError(f""labels {not_found} not found in level"")
KeyError: ""labels ['동절기'] not found in level""
","""labels ['동절기'] not found in level"""
cowidev.vax.batch.spc,31.31,True,2023-04-22T07:00:38,,
cowidev.vax.batch.sweden,14.43,True,2023-04-22T07:00:22,,
cowidev.vax.batch.switzerland,95.72,True,2023-04-22T07:01:43,,
cowidev.vax.batch.trinidad_and_tobago,6.8,True,2023-04-22T07:00:14,,
cowidev.vax.batch.ukraine,,,2023-04-22T07:00:08,,
cowidev.vax.batch.united_kingdom,16.94,True,2023-04-22T07:00:25,,
cowidev.vax.batch.united_states,12.45,True,2023-04-22T07:00:22,,
cowidev.vax.batch.uruguay,6.73,True,2023-04-22T07:00:17,,
cowidev.vax.batch.zimbabwe,3.12,True,2023-04-22T07:00:14,,
cowidev.vax.incremental.africacdc,,,2023-04-22T07:00:11,,
cowidev.vax.incremental.antigua_barbuda,,,2023-04-22T07:00:11,,
cowidev.vax.incremental.aruba,2.97,True,2023-04-22T07:00:14,,
cowidev.vax.incremental.austria,,,2023-04-22T07:00:11,,
cowidev.vax.incremental.azerbaijan,,,2023-04-22T07:00:11,,
cowidev.vax.incremental.bahrain,,,2023-04-22T07:00:11,,
cowidev.vax.incremental.bangladesh,33.91,False,2023-04-22T07:04:23,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/response.py"", line 443, in _error_catcher
    yield
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/response.py"", line 815, in read_chunked
    self._update_chunk_length()
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/response.py"", line 745, in _update_chunk_length
    line = self._fp.fp.readline()
  File ""/usr/lib/python3.10/socket.py"", line 705, in readinto
    return self._sock.recv_into(b)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/models.py"", line 760, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/response.py"", line 623, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/response.py"", line 803, in read_chunked
    with self._error_catcher():
  File ""/usr/lib/python3.10/contextlib.py"", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/response.py"", line 448, in _error_catcher
    raise ReadTimeoutError(self._pool, None, ""Read timed out."")
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='103.247.238.92', port=80): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/bangladesh.py"", line 112, in main
    Bangladesh().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/bangladesh.py"", line 98, in export
    data = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/bangladesh.py"", line 25, in read
    metrics = self._parse_metrics(soup)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/bangladesh.py"", line 74, in _parse_metrics
    single_doses = self._parse_single_doses()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/bangladesh.py"", line 38, in _parse_single_doses
    soup = get_soup(url, timeout=30)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 49, in get_response
    raise err
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 43, in get_response
    response = requests.get(source, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/api.py"", line 75, in get
    return request('get', url, params=params, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/api.py"", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/sessions.py"", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/sessions.py"", line 687, in send
    r.content
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/models.py"", line 838, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/models.py"", line 767, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='103.247.238.92', port=80): Read timed out.
","HTTPConnectionPool(host='103.247.238.92', port=80): Read timed out."
cowidev.vax.incremental.barbados,,,2023-04-22T07:00:12,,
cowidev.vax.incremental.brazil,1.85,True,2023-04-22T07:00:14,,
cowidev.vax.incremental.bulgaria,7.3,True,2023-04-22T07:00:21,,
cowidev.vax.incremental.china,20.99,True,2023-04-22T07:00:35,,
cowidev.vax.incremental.costa_rica,,,2023-04-22T07:00:14,,
cowidev.vax.incremental.croatia,0.55,True,2023-04-22T07:00:15,,
cowidev.vax.incremental.cuba,9.69,True,2023-04-22T07:00:24,,
cowidev.vax.incremental.curacao,0.87,True,2023-04-22T07:00:15,,
cowidev.vax.incremental.cyprus,2.66,True,2023-04-22T07:00:17,,
cowidev.vax.incremental.dominican_republic,11.39,False,2023-04-22T07:04:34,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 112, in main
    DominicanRepublic().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 68, in export
    data = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 26, in read
    metrics = self._parse_metrics(driver)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 35, in _parse_metrics
    metric_candidates = _find_potential_metrics(driver)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 91, in _find_potential_metrics
    h3 = _find_h3(driver)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 81, in _find_h3
    raise ValueError(""More than one element found!"")
ValueError: More than one element found!
",More than one element found!
cowidev.vax.incremental.el_salvador,9.37,True,2023-04-22T07:00:24,,
cowidev.vax.incremental.faeroe_islands,1.27,True,2023-04-22T07:00:16,,
cowidev.vax.incremental.fiji,0.0,True,2023-04-22T07:00:15,,
cowidev.vax.incremental.finland,0.56,True,2023-04-22T07:00:16,,
cowidev.vax.incremental.gabon,,,2023-04-22T07:00:16,,
cowidev.vax.incremental.georgia,6.72,True,2023-04-22T07:00:22,,
cowidev.vax.incremental.greenland,,,2023-04-22T07:00:16,,
cowidev.vax.incremental.guatemala,,,2023-04-22T07:00:16,,
cowidev.vax.incremental.guernsey,,,2023-04-22T07:00:16,,
cowidev.vax.incremental.hungary,88.19,True,2023-04-22T07:01:44,,
cowidev.vax.incremental.iceland,1.68,True,2023-04-22T07:00:18,,
cowidev.vax.incremental.india,2.75,True,2023-04-22T07:00:19,,
cowidev.vax.incremental.iran,,,2023-04-22T07:00:16,,
cowidev.vax.incremental.isle_of_man,3.45,True,2023-04-22T07:00:20,,
cowidev.vax.incremental.jamaica,9.39,True,2023-04-22T07:00:26,,
cowidev.vax.incremental.kazakhstan,130.64,False,2023-04-22T07:06:45,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/kazakhstan.py"", line 78, in main
    Kazakhstan().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/kazakhstan.py"", line 73, in export
    df = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/kazakhstan.py"", line 18, in read
    driver.get(self.source_url)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py"", line 333, in get
    self.execute(Command.GET, {'url': url})
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py"", line 321, in execute
    self.error_handler.check_response(response)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py"", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_TIMED_OUT
  (Session info: headless chrome=112.0.5615.49)

","Message: unknown error: net::ERR_CONNECTION_TIMED_OUT
  (Session info: headless chrome=112.0.5615.49)
"
cowidev.vax.incremental.kosovo,,,2023-04-22T07:00:18,,
cowidev.vax.incremental.kyrgyzstan,8.57,True,2023-04-22T07:00:26,,
cowidev.vax.incremental.laos,0.86,False,2023-04-22T07:06:45,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 703, in urlopen
    httplib_response = self._make_request(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 386, in _make_request
    self._validate_conn(conn)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 1042, in _validate_conn
    conn.connect()
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connection.py"", line 414, in connect
    self.sock = ssl_wrap_socket(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/util/ssl_.py"", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/util/ssl_.py"", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File ""/usr/lib/python3.10/ssl.py"", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File ""/usr/lib/python3.10/ssl.py"", line 1071, in _create
    self.do_handshake()
  File ""/usr/lib/python3.10/ssl.py"", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/adapters.py"", line 440, in send
    resp = conn.urlopen(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/connectionpool.py"", line 787, in urlopen
    retries = retries.increment(
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/urllib3/util/retry.py"", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.covid19.gov.la', port=443): Max retries exceeded with url: /index.php (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/laos.py"", line 101, in main
    Laos().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/laos.py"", line 88, in export
    data = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/laos.py"", line 21, in read
    soup = get_soup(self.source_url)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 49, in get_response
    raise err
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 43, in get_response
    response = requests.get(source, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/api.py"", line 75, in get
    return request('get', url, params=params, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/api.py"", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/sessions.py"", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/sessions.py"", line 645, in send
    r = adapter.send(request, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/requests/adapters.py"", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.covid19.gov.la', port=443): Max retries exceeded with url: /index.php (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)')))
","HTTPSConnectionPool(host='www.covid19.gov.la', port=443): Max retries exceeded with url: /index.php (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)')))"
cowidev.vax.incremental.macao,7.18,False,2023-04-22T07:06:53,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/macao.py"", line 89, in main
    Macao().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/macao.py"", line 74, in export
    data = self.read()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/macao.py"", line 22, in read
    iframe_url = self._get_iframe_url(driver)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/macao.py"", line 30, in _get_iframe_url
    elem = driver.find_element_by_id(""ICovid19Monitor"")
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py"", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py"", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py"", line 321, in execute
    self.error_handler.check_response(response)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py"", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {""method"":""css selector"",""selector"":""[id=""ICovid19Monitor""]""}
  (Session info: headless chrome=112.0.5615.49)

","Message: no such element: Unable to locate element: {""method"":""css selector"",""selector"":""[id=""ICovid19Monitor""]""}
  (Session info: headless chrome=112.0.5615.49)
"
cowidev.vax.incremental.moldova,,,2023-04-22T07:00:19,,
cowidev.vax.incremental.monaco,96.88,True,2023-04-22T07:01:56,,
cowidev.vax.incremental.mongolia,1.61,True,2023-04-22T07:00:22,,
cowidev.vax.incremental.montenegro,1.17,True,2023-04-22T07:00:22,,
cowidev.vax.incremental.morocco,,,2023-04-22T07:00:21,,
cowidev.vax.incremental.myanmar,,,2023-04-22T07:00:21,,
cowidev.vax.incremental.nepal,,,2023-04-22T07:00:21,,
cowidev.vax.incremental.north_macedonia,,,2023-04-22T07:00:21,,
cowidev.vax.incremental.northern_cyprus,5.83,True,2023-04-22T07:00:27,,
cowidev.vax.incremental.paho,82.5,False,2023-04-22T07:08:15,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 195, in main
    PAHO().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 190, in export
    df = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 167, in pipeline
    df.pipe(self.pipe_check_columns)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 122, in pipe_check_columns
    raise ValueError(f""Missing column fields: {columns_missing}. Present columns are: {df.columns}"")
ValueError: Missing column fields: {'Country/ Territory', 'Total doses', 'Country code', 'First dose', 'Single dose', 'Second dose', '1st additional dose', '2nd additional dose'}. Present columns are: Index(['date,location,total_vaccinations,people_vaccinated,people_fully_vaccinated,total_boosters,new_vaccinations,new_vaccinations_interpolated,new_people_vaccinated_interpolated,new_vaccinations_smoothed,new_people_vaccinated_smoothed', 'date'], dtype='object')
","Missing column fields: {'Country/ Territory', 'Total doses', 'Country code', 'First dose', 'Single dose', 'Second dose', '1st additional dose', '2nd additional dose'}. Present columns are: Index(['date,location,total_vaccinations,people_vaccinated,people_fully_vaccinated,total_boosters,new_vaccinations,new_vaccinations_interpolated,new_people_vaccinated_interpolated,new_vaccinations_smoothed,new_people_vaccinated_smoothed', 'date'], dtype='object')"
cowidev.vax.incremental.pakistan,,,2023-04-22T07:00:22,,
cowidev.vax.incremental.philippines,,,2023-04-22T07:00:22,,
cowidev.vax.incremental.poland,1.93,True,2023-04-22T07:00:24,,
cowidev.vax.incremental.qatar,,,2023-04-22T07:00:22,,
cowidev.vax.incremental.russia,35.86,True,2023-04-22T07:00:58,,
cowidev.vax.incremental.saint_lucia,,,2023-04-22T07:00:22,,
cowidev.vax.incremental.serbia,7.33,True,2023-04-22T07:00:29,,
cowidev.vax.incremental.south_africa,,,2023-04-22T07:00:22,,
cowidev.vax.incremental.spain,14.41,True,2023-04-22T07:00:36,,
cowidev.vax.incremental.sri_lanka,,,2023-04-22T07:00:22,,
cowidev.vax.incremental.suriname,15.47,True,2023-04-22T07:00:38,,
cowidev.vax.incremental.taiwan,20.07,True,2023-04-22T07:00:44,,
cowidev.vax.incremental.thailand,5.36,True,2023-04-22T07:00:29,,
cowidev.vax.incremental.turkey,,,2023-04-22T07:00:24,,
cowidev.vax.incremental.united_arab_emirates,,,2023-04-22T07:00:24,,
cowidev.vax.incremental.vietnam,,,2023-04-22T07:00:24,,
cowidev.vax.incremental.who,30.51,True,2023-04-22T07:00:54,,
cowidev.vax.incremental.zambia,1.6,True,2023-04-22T07:00:26,,
