module,execution_time (sec),success,timestamp,error,error_short
cowidev.vax.batch.argentina,13.43,True,2023-04-07T07:00:20,,
cowidev.vax.batch.australia,0.24,False,2023-04-07T07:01:54,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/australia.py"", line 244, in main
    Australia().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/australia.py"", line 216, in export
    df = self.read().pipe(self.pipeline)  # Use with attach=False
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/australia.py"", line 160, in pipeline
    .pipe(self.make_monotonic)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/utils/base.py"", line 120, in make_monotonic
    return mkm(
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/utils.py"", line 23, in make_monotonic
    return make_monotonic_new(df, column_date, column_metrics, max_removed_rows)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/utils.py"", line 94, in make_monotonic_new
    raise Exception(
Exception: 1 chunks of lengths 19 have been NaNed for metric people_vaccinated. That is more than maximum allowed (10) by make_monotonic() - check the data. Check dates ['2023-03-16']
",1 chunks of lengths 19 have been NaNed for metric people_vaccinated. That is more than maximum allowed (10) by make_monotonic() - check the data. Check dates ['2023-03-16']
cowidev.vax.batch.austria_old,,,2023-04-07T07:00:07,,
cowidev.vax.batch.belgium,7.13,True,2023-04-07T07:00:14,,
cowidev.vax.batch.bolivia,5.48,True,2023-04-07T07:00:12,,
cowidev.vax.batch.canada,4.94,False,2023-04-07T07:01:59,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/canada.py"", line 282, in main
    Canada().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/canada.py"", line 270, in export
    df = df.pipe(self.pipeline, df_man)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/canada.py"", line 250, in pipeline
    .pipe(self.pipe_make_monotonic)[
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/canada.py"", line 230, in pipe_make_monotonic
    df = df.pipe(self.make_monotonic, max_removed_rows=self.max_removed_rows)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/utils/base.py"", line 120, in make_monotonic
    return mkm(
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/utils.py"", line 23, in make_monotonic
    return make_monotonic_new(df, column_date, column_metrics, max_removed_rows)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/utils.py"", line 94, in make_monotonic_new
    raise Exception(
Exception: 1 chunks of lengths 36 have been NaNed for metric people_vaccinated. That is more than maximum allowed (22) by make_monotonic() - check the data. Check dates ['2023-01-26']
",1 chunks of lengths 36 have been NaNed for metric people_vaccinated. That is more than maximum allowed (22) by make_monotonic() - check the data. Check dates ['2023-01-26']
cowidev.vax.batch.chile,1.12,True,2023-04-07T07:00:08,,
cowidev.vax.batch.czechia,18.09,True,2023-04-07T07:00:25,,
cowidev.vax.batch.denmark,,,2023-04-07T07:00:07,,
cowidev.vax.batch.ecdc,90.01,True,2023-04-07T07:01:37,,
cowidev.vax.batch.ecuador,,,2023-04-07T07:00:07,,
cowidev.vax.batch.estonia,0.68,True,2023-04-07T07:00:08,,
cowidev.vax.batch.france,7.87,True,2023-04-07T07:00:15,,
cowidev.vax.batch.germany,0.24,True,2023-04-07T07:00:07,,
cowidev.vax.batch.greece,13.54,True,2023-04-07T07:00:20,,
cowidev.vax.batch.hong_kong,13.84,True,2023-04-07T07:00:21,,
cowidev.vax.batch.indonesia,,,2023-04-07T07:00:07,,
cowidev.vax.batch.ireland,5.59,True,2023-04-07T07:00:13,,
cowidev.vax.batch.israel,9.16,True,2023-04-07T07:00:16,,
cowidev.vax.batch.italy,11.87,True,2023-04-07T07:00:19,,
cowidev.vax.batch.japan,43.29,True,2023-04-07T07:00:50,,
cowidev.vax.batch.jersey,5.93,True,2023-04-07T07:00:13,,
cowidev.vax.batch.latvia,63.86,True,2023-04-07T07:01:11,,
cowidev.vax.batch.lithuania,7.03,True,2023-04-07T07:00:14,,
cowidev.vax.batch.luxembourg,2.55,True,2023-04-07T07:00:09,,
cowidev.vax.batch.malaysia,0.92,True,2023-04-07T07:00:08,,
cowidev.vax.batch.malta,1.21,True,2023-04-07T07:00:08,,
cowidev.vax.batch.netherlands,,,2023-04-07T07:00:07,,
cowidev.vax.batch.new_zealand,1.4,False,2023-04-07T07:02:00,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/new_zealand.py"", line 116, in main
    NewZealand().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/new_zealand.py"", line 111, in export
    df = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/new_zealand.py"", line 43, in read
    df = read_xlsx_from_url(link, sheet_name=""Date"")
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/download.py"", line 47, in read_xlsx_from_url
    df = pd.read_excel(tmp.name, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/util/_decorators.py"", line 311, in wrapper
    return func(*args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/excel/_base.py"", line 364, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/excel/_base.py"", line 1195, in __init__
    raise ValueError(
ValueError: Excel file format cannot be determined, you must specify an engine manually.
","Excel file format cannot be determined, you must specify an engine manually."
cowidev.vax.batch.norway,0.41,True,2023-04-07T07:00:07,,
cowidev.vax.batch.peru,5.54,True,2023-04-07T07:00:12,,
cowidev.vax.batch.portugal,,,2023-04-07T07:00:07,,
cowidev.vax.batch.romania,31.46,True,2023-04-07T07:00:38,,
cowidev.vax.batch.saudi_arabia,3.73,True,2023-04-07T07:00:11,,
cowidev.vax.batch.singapore,5.9,True,2023-04-07T07:00:13,,
cowidev.vax.batch.slovakia,46.29,True,2023-04-07T07:00:53,,
cowidev.vax.batch.slovenia,2.94,True,2023-04-07T07:00:10,,
cowidev.vax.batch.south_korea,40.52,True,2023-04-07T07:02:41,,
cowidev.vax.batch.spc,30.32,True,2023-04-07T07:00:38,,
cowidev.vax.batch.sweden,11.17,True,2023-04-07T07:00:19,,
cowidev.vax.batch.switzerland,85.99,True,2023-04-07T07:01:34,,
cowidev.vax.batch.trinidad_and_tobago,4.99,True,2023-04-07T07:00:13,,
cowidev.vax.batch.ukraine,,,2023-04-07T07:00:08,,
cowidev.vax.batch.united_kingdom,12.55,True,2023-04-07T07:00:21,,
cowidev.vax.batch.united_states,9.25,False,2023-04-07T07:02:50,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/united_states.py"", line 192, in main
    UnitedStates().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/united_states.py"", line 179, in export
    df_manufacturer = self.read_manufacturer().pipe(self.pipeline_manufacturer)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/united_states.py"", line 172, in pipeline_manufacturer
    df = df.pipe(self.make_monotonic, ""vaccine"")
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/utils/base.py"", line 109, in make_monotonic
    _df = mkm(
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/utils.py"", line 23, in make_monotonic
    return make_monotonic_new(df, column_date, column_metrics, max_removed_rows)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/utils.py"", line 94, in make_monotonic_new
    raise Exception(
Exception: 1 chunks of lengths 26 have been NaNed for metric total_vaccinations. That is more than maximum allowed (10) by make_monotonic() - check the data. Check dates ['2023-03-22']
",1 chunks of lengths 26 have been NaNed for metric total_vaccinations. That is more than maximum allowed (10) by make_monotonic() - check the data. Check dates ['2023-03-22']
cowidev.vax.batch.uruguay,7.77,True,2023-04-07T07:00:18,,
cowidev.vax.batch.zimbabwe,2.89,True,2023-04-07T07:00:13,,
cowidev.vax.incremental.africacdc,,,2023-04-07T07:00:11,,
cowidev.vax.incremental.antigua_barbuda,,,2023-04-07T07:00:11,,
cowidev.vax.incremental.aruba,2.83,True,2023-04-07T07:00:14,,
cowidev.vax.incremental.austria,,,2023-04-07T07:00:12,,
cowidev.vax.incremental.azerbaijan,,,2023-04-07T07:00:12,,
cowidev.vax.incremental.bahrain,,,2023-04-07T07:00:12,,
cowidev.vax.incremental.bangladesh,40.39,True,2023-04-07T07:00:53,,
cowidev.vax.incremental.barbados,,,2023-04-07T07:00:12,,
cowidev.vax.incremental.brazil,1.28,True,2023-04-07T07:00:14,,
cowidev.vax.incremental.bulgaria,8.24,True,2023-04-07T07:00:21,,
cowidev.vax.incremental.china,20.67,True,2023-04-07T07:00:33,,
cowidev.vax.incremental.costa_rica,,,2023-04-07T07:00:13,,
cowidev.vax.incremental.croatia,1.41,True,2023-04-07T07:00:14,,
cowidev.vax.incremental.cuba,6.74,True,2023-04-07T07:00:20,,
cowidev.vax.incremental.curacao,1.25,True,2023-04-07T07:00:14,,
cowidev.vax.incremental.cyprus,2.7,True,2023-04-07T07:00:16,,
cowidev.vax.incremental.dominican_republic,11.49,False,2023-04-07T07:03:02,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 112, in main
    DominicanRepublic().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 68, in export
    data = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 26, in read
    metrics = self._parse_metrics(driver)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 35, in _parse_metrics
    metric_candidates = _find_potential_metrics(driver)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 91, in _find_potential_metrics
    h3 = _find_h3(driver)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 81, in _find_h3
    raise ValueError(""More than one element found!"")
ValueError: More than one element found!
",More than one element found!
cowidev.vax.incremental.el_salvador,6.41,True,2023-04-07T07:00:20,,
cowidev.vax.incremental.faeroe_islands,1.11,True,2023-04-07T07:00:15,,
cowidev.vax.incremental.fiji,0.0,True,2023-04-07T07:00:14,,
cowidev.vax.incremental.finland,0.8,True,2023-04-07T07:00:15,,
cowidev.vax.incremental.gabon,,,2023-04-07T07:00:14,,
cowidev.vax.incremental.georgia,4.9,True,2023-04-07T07:00:19,,
cowidev.vax.incremental.greenland,0.15,False,2023-04-07T07:03:02,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/greenland.py"", line 76, in main
    Greenland().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/greenland.py"", line 63, in export
    data = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/greenland.py"", line 17, in read
    data = self._parse_data(soup)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/greenland.py"", line 21, in _parse_data
    return {**self._parse_data_metrics(soup), **self._parse_data_date(soup)}
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/greenland.py"", line 31, in _parse_data_metrics
    assert len(counter_1) == len(counter_2) == 1
AssertionError
",
cowidev.vax.incremental.guatemala,,,2023-04-07T07:00:15,,
cowidev.vax.incremental.guernsey,0.92,False,2023-04-07T07:03:03,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/guernsey.py"", line 78, in main
    Guernsey().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/guernsey.py"", line 64, in export
    data = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/guernsey.py"", line 17, in read
    df = self.parse_data(soup)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/guernsey.py"", line 26, in parse_data
    soup.find(""div"", class_=""ace-notice-paragraph"").text, self._regex_date, ""%d %B %Y""
AttributeError: 'NoneType' object has no attribute 'text'
",'NoneType' object has no attribute 'text'
cowidev.vax.incremental.hungary,80.22,True,2023-04-07T07:01:35,,
cowidev.vax.incremental.iceland,2.15,True,2023-04-07T07:00:18,,
cowidev.vax.incremental.india,2.62,True,2023-04-07T07:00:19,,
cowidev.vax.incremental.iran,,,2023-04-07T07:00:17,,
cowidev.vax.incremental.isle_of_man,2.93,True,2023-04-07T07:00:20,,
cowidev.vax.incremental.jamaica,5.1,True,2023-04-07T07:00:23,,
cowidev.vax.incremental.kazakhstan,6.78,True,2023-04-07T07:00:25,,
cowidev.vax.incremental.kosovo,0.12,False,2023-04-07T07:03:03,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/kosovo.py"", line 82, in main
    Kosovo().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/kosovo.py"", line 77, in export
    df = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/kosovo.py"", line 22, in read
    soup = get_soup(self.source_url, verify=False)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 52, in get_response
    raise ValueError(
ValueError: Source https://msh.rks-gov.net/sq/statistikat-covid-19/ not reached! Error code 404 Not Found
",Source https://msh.rks-gov.net/sq/statistikat-covid-19/ not reached! Error code 404 Not Found
cowidev.vax.incremental.kyrgyzstan,2.25,True,2023-04-07T07:00:21,,
cowidev.vax.incremental.laos,1.68,True,2023-04-07T07:03:04,,
cowidev.vax.incremental.macao,13.38,True,2023-04-07T07:00:32,,
cowidev.vax.incremental.moldova,,,2023-04-07T07:00:19,,
cowidev.vax.incremental.monaco,94.48,True,2023-04-07T07:01:54,,
cowidev.vax.incremental.mongolia,1.14,True,2023-04-07T07:00:20,,
cowidev.vax.incremental.montenegro,0.89,True,2023-04-07T07:00:21,,
cowidev.vax.incremental.morocco,,,2023-04-07T07:00:20,,
cowidev.vax.incremental.myanmar,,,2023-04-07T07:00:20,,
cowidev.vax.incremental.nepal,,,2023-04-07T07:00:20,,
cowidev.vax.incremental.north_macedonia,,,2023-04-07T07:00:20,,
cowidev.vax.incremental.northern_cyprus,6.02,True,2023-04-07T07:00:26,,
cowidev.vax.incremental.paho,82.84,False,2023-04-07T07:04:27,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 195, in main
    PAHO().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 190, in export
    df = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 167, in pipeline
    df.pipe(self.pipe_check_columns)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 122, in pipe_check_columns
    raise ValueError(f""Missing column fields: {columns_missing}. Present columns are: {df.columns}"")
ValueError: Missing column fields: {'2nd additional dose', 'Country code', 'Country/ Territory', 'First dose', 'Total doses', '1st additional dose', 'Single dose', 'Second dose'}. Present columns are: Index(['date,location,total_vaccinations,people_vaccinated,people_fully_vaccinated,total_boosters,new_vaccinations,new_vaccinations_interpolated,new_people_vaccinated_interpolated,new_vaccinations_smoothed,new_people_vaccinated_smoothed', 'date'], dtype='object')
","Missing column fields: {'2nd additional dose', 'Country code', 'Country/ Territory', 'First dose', 'Total doses', '1st additional dose', 'Single dose', 'Second dose'}. Present columns are: Index(['date,location,total_vaccinations,people_vaccinated,people_fully_vaccinated,total_boosters,new_vaccinations,new_vaccinations_interpolated,new_people_vaccinated_interpolated,new_vaccinations_smoothed,new_people_vaccinated_smoothed', 'date'], dtype='object')"
cowidev.vax.incremental.pakistan,,,2023-04-07T07:00:20,,
cowidev.vax.incremental.philippines,,,2023-04-07T07:00:20,,
cowidev.vax.incremental.poland,0.74,True,2023-04-07T07:00:21,,
cowidev.vax.incremental.qatar,,,2023-04-07T07:00:20,,
cowidev.vax.incremental.russia,23.01,True,2023-04-07T07:00:43,,
cowidev.vax.incremental.saint_lucia,,,2023-04-07T07:00:20,,
cowidev.vax.incremental.serbia,10.3,True,2023-04-07T07:00:31,,
cowidev.vax.incremental.south_africa,,,2023-04-07T07:00:21,,
cowidev.vax.incremental.spain,8.62,True,2023-04-07T07:00:29,,
cowidev.vax.incremental.sri_lanka,,,2023-04-07T07:00:21,,
cowidev.vax.incremental.suriname,15.09,True,2023-04-07T07:00:36,,
cowidev.vax.incremental.taiwan,8.77,False,2023-04-07T07:04:36,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/taiwan.py"", line 179, in main
    Taiwan().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/taiwan.py"", line 165, in export
    data = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/taiwan.py"", line 35, in read
    df = self._parse_table(url_pdf)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/taiwan.py"", line 62, in _parse_table
    raise ValueError(f""Table 1: format has changed! It has shape {df.shape} instead of {shape_expected}"")
ValueError: Table 1: format has changed! It has shape (42, 4) instead of (39, 4)
","Table 1: format has changed! It has shape (42, 4) instead of (39, 4)"
cowidev.vax.incremental.thailand,6.8,True,2023-04-07T07:00:28,,
cowidev.vax.incremental.turkey,6.33,False,2023-04-07T07:04:42,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/turkey.py"", line 60, in main
    data = read(source).pipe(pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/turkey.py"", line 19, in read
    soup = get_soup(source)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 83, in get_soup
    response = get_response(source, request_method, use_proxy, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 52, in get_response
    raise ValueError(
ValueError: Source https://covid19asi.saglik.gov.tr/ not reached! Error code 504 Gateway Timeout
",Source https://covid19asi.saglik.gov.tr/ not reached! Error code 504 Gateway Timeout
cowidev.vax.incremental.united_arab_emirates,,,2023-04-07T07:00:21,,
cowidev.vax.incremental.vietnam,,,2023-04-07T07:00:21,,
cowidev.vax.incremental.who,32.62,True,2023-04-07T07:00:54,,
cowidev.vax.incremental.zambia,0.97,True,2023-04-07T07:00:22,,
